### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by raupachz** [pavlov99/docker-gnuplot#1]
Hi there,

thanks for the Dockerfile!

Unfortunately, in its current state, it is rather limited because fonts are missing.

```
$ docker pull pavlov99/gnuplot
$ docker run -it --rm pavlov99/gnuplot /bin/sh
/ # fc-list
/ #
```

For example lets render some basic plot with a title:

```
$ docker run -it --rm -v `pwd`:/tmp pavlov99/gnuplot gnuplot
gnuplot> cd "/tmp"
gnuplot> set terminal pngcairo
gnuplot> set output "image.png"
gnuplot> set title "Untitled"
gnuplot> plot sin(x)
```

There won't be any text in this image because there are no fonts in your image. 

Pretty easy to solve. Just add something like `RUN apk --no-cache add ttf-ubuntu-font-family fontconfig && fc-cache -f` to your Docker file.

In know, this repo is two years old, but I find it still useful. Maybe this helps someone else stumbling upon it.

**Comment by pavlov99** [comment]
Great suggestion, @raupachz. Let me add it!

**Comment by pavlov99** [comment]
@raupachz please let me know if that works https://github.com/pavlov99/docker-gnuplot/commit/c2b845f39798d50338491bb36f0c1d9257ee6f10

**Comment by pavlov99** [comment]
Included standard fonts as well.
Closing the issue.
